export const PROVINCE_OPTIONS = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Cần Thơ",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
] as const;

export const CATEGORY_OPTIONS = [
  "Y tế",
  "Công nghệ thông tin",
  "Xây dựng",
  "Giáo dục",
  "Nông nghiệp",
  "Điện lực",
  "Giao thông",
  "Môi trường",
  "Thiết bị văn phòng",
  "Dịch vụ tư vấn",
  "An ninh",
  "Khác",
] as const;

export const KEYWORD_OPTIONS = [
  "mua sắm",
  "hóa chất",
  "vật tư",
  "thiết bị",
  "xây lắp",
  "tư vấn",
  "phần mềm",
  "máy tính",
  "hạ tầng",
  "giao thông",
  "điện",
  "nước",
  "bệnh viện",
  "trường học",
  "giám sát",
  "thi công",
  "bảo trì",
  "dịch vụ",
] as const;

export const SORT_LABELS = {
  publishedAt: "Ngày đăng",
  budget: "Ngân sách",
  matchScore: "Điểm phù hợp",
  title: "Tên gói thầu",
  inviter: "Bên mời thầu",
} as const;

export const PAGE_SIZE_OPTIONS = [10, 20, 50] as const;

export type SortBy = keyof typeof SORT_LABELS;
export type SortOrder = "asc" | "desc";
